name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Thay đổi nếu bạn sử dụng nhánh khác

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Hoặc '20'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Sử dụng token đã lưu
      run: firebase deploy --token $FIREBASE_TOKEN --project mmq666-baea1
